services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: validra_api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    volumes:
      - .:/app
    restart: unless-stopped

  ollama:
    profiles:
      - ollama
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./start.sh:/start.sh
    entrypoint: ["/bin/sh", "/start.sh"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  ollama_data:
